# Prompt Builder — Tag Data
# Auto-generated from illus-prompt-builder.html

PALETTE = [
    '#f9a8d4', '#f87171', '#fb923c', '#fbbf24', '#a3e635',
    '#34d399', '#22d3ee', '#67e8f9', '#818cf8', '#c084fc',
    '#e879f9', '#94a3b8',
]

SECTIONS = [
    {
        'id': 'quality',
        'label': 'Quality',
        'color': '#fb923c',
        'randomize': False,
        'categories': [
            {
                'label': 'Boosters',
                'single': False,
                'chips': [
                    ('masterpiece', 'masterpiece'),
                    ('best quality', 'best quality'),
                    ('amazing quality', 'amazing quality'),
                    ('very aesthetic', 'very aesthetic'),
                    ('newest', 'newest'),
                    ('perfect quality', 'perfect quality'),
                    ('high quality', 'high quality'),
                    ('eye-catching', 'absolutely eye-catching'),
                    ('detailed', 'detailed'),
                    ('ultra detailed', 'ultra detailed'),
                    ('lowres', 'lowres'),
                    ('worst quality', 'worst quality'),
                    ('bad quality', 'bad quality'),
                    ('low quality', 'low quality'),
                    ('displeasing', 'displeasing'),
                    ('very displeasing', 'very displeasing'),
                    ('bad anatomy', 'bad anatomy'),
                    ('bad hands', 'bad hands'),
                    ('extra digits', 'extra digits'),
                    ('fewer digits', 'fewer digits'),
                    ('missing fingers', 'missing fingers'),
                    ('extra limbs', 'extra limbs'),
                    ('jpeg artifacts', 'jpeg artifacts'),
                    ('watermark', 'watermark'),
                    ('signature', 'signature'),
                    ('username', 'username'),
                    ('artist name', 'artist name'),
                    ('text', 'text'),
                    ('scan artifacts', 'scan artifacts'),
                    ('chromatic aberration', 'chromatic aberration'),
                    ('artistic error', 'artistic error'),
                    ('oldest', 'oldest'),
                    ('old', 'old'),
                    ('early', 'early'),
                    ('unfinished', 'unfinished'),
                    ('multiple views', 'multiple views'),
                ]
            },
            {
                'label': 'Resolution',
                'single': False,
                'chips': [
                    ('absurdres', 'absurdres'),
                    ('highres', 'highres'),
                    ('4k', '4k'),
                    ('8k', '8k'),
                ]
            },
        ]
    },
    {
        'id': 'artist',
        'label': 'Artist',
        'color': '#94a3b8',
        'randomize': False,
        'categories': [
            {
                'label': 'By',
                'single': False,
                'chips': [
                    ('wlop', 'by wlop'),
                    ('ask (askzy)', 'by ask (askzy)'),
                    ('ciloranko', 'by ciloranko'),
                    ('ningen mame', 'by ningen mame'),
                    ('sho (sho lwlw)', 'by sho (sho lwlw)'),
                    ('fuzichoco', 'by fuzichoco'),
                    ('hiten (hitenkei)', 'by hiten (hitenkei)'),
                    ('chen bin', 'by chen bin'),
                    ('tsurusaki takahiro', 'by tsurusaki takahiro'),
                    ('matanonki', 'by matanonki'),
                    ('tianliang duohe fangdongye', 'by tianliang duohe fangdongye'),
                    ('modare', 'by modare'),
                    ('rhasta', 'by rhasta'),
                    ('kedama milk', 'by kedama milk'),
                    ('rei (sanbonzakura)', 'by rei (sanbonzakura)'),
                    ('alpha (alpha91)', 'by alpha (alpha91)'),
                    ('houkisei', 'by houkisei'),
                    ('nawakena', 'by nawakena'),
                    ('atdan', 'by atdan'),
                    ('akihiko yoshida', 'by akihiko yoshida'),
                ]
            },
        ]
    },
    {
        'id': 'count',
        'label': 'Subject Count',
        'color': '#818cf8',
        'randomize': False,
        'categories': [
            {
                'label': 'Count',
                'single': True,
                'chips': [
                    ('1girl', '1girl, solo'),
                    ('1boy', '1boy, solo'),
                    ('2girls', '2girls, duo'),
                    ('2boys', '2boys, duo'),
                    ('1girl 1boy', '1girl, 1boy, duo'),
                    ('3girls', '3girls, multiple girls'),
                    ('3boys', '3boys, multiple boys'),
                    ('group', 'multiple girls, group'),
                    ('no humans', 'no humans'),
                ]
            },
        ]
    },
    {
        'id': 'race',
        'label': 'Race',
        'color': '#f9a8d4',
        'randomize': True,
        'categories': [
            {
                'label': 'Human',
                'single': True,
                'chips': [
                    ('human', 'human'),
                ]
            },
            {
                'label': 'Kemonomimi',
                'single': False,
                'chips': [
                    ('fox girl › fox girl', 'fox girl'),
                    ('fox girl › fox ears', 'fox ears'),
                    ('fox girl › fox tail', 'fox tail'),
                    ('fox girl › kitsune', 'kitsune'),
                    ('fox girl › multiple tails', 'multiple tails'),
                    ('fox girl › nine-tailed fox', 'nine-tailed fox'),
                    ('cat girl › cat girl', 'cat girl'),
                    ('cat girl › cat ears', 'cat ears'),
                    ('cat girl › cat tail', 'cat tail'),
                    ('wolf girl › wolf girl', 'wolf girl'),
                    ('wolf girl › wolf ears', 'wolf ears'),
                    ('wolf girl › wolf tail', 'wolf tail'),
                    ('bunny girl › bunny girl', 'bunny girl'),
                    ('bunny girl › rabbit ears', 'rabbit ears'),
                    ('bunny girl › rabbit tail', 'rabbit tail'),
                    ('dog girl › dog girl', 'dog girl'),
                    ('dog girl › dog ears', 'dog ears'),
                    ('dog girl › dog tail', 'dog tail'),
                    ('deer girl › deer girl', 'deer girl'),
                    ('deer girl › deer ears', 'deer ears'),
                    ('deer girl › antlers', 'antlers'),
                    ('deer girl › deer tail', 'deer tail'),
                    ('dragon girl › dragon girl', 'dragon girl'),
                    ('dragon girl › dragon horns', 'dragon horns'),
                    ('dragon girl › dragon tail', 'dragon tail'),
                    ('dragon girl › dragon wings', 'dragon wings'),
                    ('dragon girl › scales', 'scales'),
                    ('horse girl › horse girl', 'horse girl'),
                    ('horse girl › horse ears', 'horse ears'),
                    ('horse girl › horse tail', 'horse tail'),
                    ('animal ears', 'animal ears'),
                    ('fluffy tail', 'fluffy tail'),
                ]
            },
            {
                'label': 'Fantasy',
                'single': False,
                'chips': [
                    ('elf › elf', 'elf'),
                    ('elf › pointy ears', 'pointy ears'),
                    ('elf › dark elf', 'dark elf'),
                    ('elf › dark skin', 'dark skin'),
                    ('demon › demon girl', 'demon girl'),
                    ('demon › demon horns', 'demon horns'),
                    ('demon › demon tail', 'demon tail'),
                    ('demon › demon wings', 'demon wings'),
                    ('demon › succubus', 'succubus'),
                    ('demon › tiefling', 'tiefling'),
                    ('angel › angel', 'angel'),
                    ('angel › angel wings', 'angel wings'),
                    ('angel › halo', 'halo'),
                    ('vampire › vampire', 'vampire'),
                    ('vampire › fangs', 'fangs'),
                    ('vampire › bat wings', 'bat wings'),
                    ('oni › oni', 'oni'),
                    ('oni › oni horns', 'oni horns'),
                    ('oni › club', 'club (weapon)'),
                    ('fairy › fairy', 'fairy'),
                    ('fairy › fairy wings', 'fairy wings'),
                    ('fairy › pixie', 'pixie'),
                    ('undead › undead', 'undead'),
                    ('undead › zombie', 'zombie'),
                    ('undead › skeleton', 'skeleton'),
                    ('undead › lich', 'lich'),
                    ('undead › ghost', 'ghost'),
                    ('witch', 'witch'),
                    ('mermaid', 'mermaid'),
                    ('slime girl', 'slime girl'),
                    ('dwarf', 'dwarf'),
                    ('tengu', 'tengu'),
                ]
            },
            {
                'label': 'Demi-human',
                'single': False,
                'chips': [
                    ('harpy › harpy', 'harpy'),
                    ('harpy › bird wings', 'bird wings'),
                    ('harpy › feathered wings', 'feathered wings'),
                    ('harpy › talons', 'talons'),
                    ('harpy › feathers', 'feathers'),
                    ('lamia › lamia', 'lamia'),
                    ('lamia › snake tail', 'snake tail'),
                    ('lamia › scales', 'scales'),
                    ('lamia › forked tongue', 'forked tongue'),
                    ('arachne › arachne', 'arachne'),
                    ('arachne › spider girl', 'spider girl'),
                    ('arachne › spider legs', 'extra legs'),
                    ('arachne › spider web', 'spider web'),
                    ('centaur › centaur', 'centaur'),
                    ('centaur › horse legs', 'horse legs'),
                    ('monstergirl', 'monster girl'),
                ]
            },
            {
                'label': 'Sci-fi',
                'single': False,
                'chips': [
                    ('android › android', 'android'),
                    ('android › robot girl', 'robot girl'),
                    ('android › mechanical body', 'mechanical body'),
                    ('android › robot joints', 'robot joints'),
                    ('android › joint seal', 'joint seal'),
                    ('android › artificial eye', 'artificial eye'),
                    ('cyborg › cyborg', 'cyborg'),
                    ('cyborg › mechanical arm', 'mechanical arm'),
                    ('cyborg › mechanical legs', 'mechanical legs'),
                    ('cyborg › cybernetic eye', 'cybernetic eye'),
                    ('cyborg › mechanical parts', 'mechanical parts'),
                    ('mecha musume › mecha musume', 'mecha musume'),
                    ('mecha musume › headgear', 'headgear'),
                    ('mecha musume › shoulder armor', 'shoulder armor'),
                    ('mecha musume › mechanical wings', 'mechanical wings'),
                    ('alien', 'alien'),
                    ('antenna', 'antenna'),
                    ('visor', 'visor'),
                    ('science fiction', 'science fiction'),
                ]
            },
        ]
    },
    {
        'id': 'eyes',
        'label': 'Eyes',
        'color': '#67e8f9',
        'randomize': True,
        'categories': [
            {
                'label': 'Color',
                'single': True,
                'chips': [
                    ('red', 'red eyes'),
                    ('orange', 'orange eyes'),
                    ('yellow', 'yellow eyes'),
                    ('amber', 'amber eyes'),
                    ('green', 'green eyes'),
                    ('teal', 'teal eyes'),
                    ('blue', 'blue eyes'),
                    ('purple', 'purple eyes'),
                    ('pink', 'pink eyes'),
                    ('brown', 'brown eyes'),
                    ('grey', 'grey eyes'),
                    ('black', 'black eyes'),
                    ('gold', 'gold eyes'),
                    ('silver', 'silver eyes'),
                    ('white', 'white eyes'),
                    ('heterochromia › heterochromia', 'heterochromia'),
                    ('heterochromia › odd', 'odd eyes'),
                    ('heterochromia › multicolored', 'multicolored eyes'),
                    ('heterochromia › red eye', 'red eye'),
                    ('heterochromia › orange eye', 'orange eye'),
                    ('heterochromia › yellow eye', 'yellow eye'),
                    ('heterochromia › amber eye', 'amber eye'),
                    ('heterochromia › green eye', 'green eye'),
                    ('heterochromia › teal eye', 'teal eye'),
                    ('heterochromia › blue eye', 'blue eye'),
                    ('heterochromia › purple eye', 'purple eye'),
                    ('heterochromia › pink eye', 'pink eye'),
                    ('heterochromia › brown eye', 'brown eye'),
                    ('heterochromia › grey eye', 'grey eye'),
                    ('heterochromia › black eye', 'black eye'),
                    ('heterochromia › gold eye', 'gold eye'),
                    ('heterochromia › silver eye', 'silver eye'),
                    ('heterochromia › white eye', 'white eye'),
                ]
            },
            {
                'label': 'Shape',
                'single': True,
                'chips': [
                    ('tareme', 'tareme'),
                    ('tsurime', 'tsurime'),
                    ('round', 'round eyes'),
                    ('wide', 'wide eyes'),
                    ('hooded', 'half-closed eyes'),
                    ('aqua', 'aqua eyes'),
                    ('monolid', 'single eyelid'),
                ]
            },
            {
                'label': 'Pupils',
                'single': False,
                'chips': [
                    ('white', 'white pupils'),
                    ('no', 'no pupils'),
                    ('slit', 'slit pupils'),
                    ('vertical', 'vertical-slit pupils'),
                    ('heart', 'heart-shaped pupils'),
                    ('star', 'star-shaped pupils'),
                    ('cross', 'cross-shaped pupils'),
                    ('spiral', 'spiral pupils'),
                    ('dilated', 'dilated pupils'),
                ]
            },
            {
                'label': 'Type',
                'single': False,
                'chips': [
                    ('gradient', 'gradient eyes'),
                    ('two-tone', 'two-tone eyes'),
                    ('glowing', 'glowing eyes'),
                    ('empty', 'empty eyes'),
                    ('sparkling', 'sparkling eyes'),
                    ('ringed', 'ringed eyes'),
                    ('symbol', 'symbol-shaped pupils'),
                    ('glassy', 'glassy eyes'),
                    ('glowing iris', 'glowing'),
                ]
            },
            {
                'label': 'Details',
                'single': False,
                'chips': [
                    ('long eyelashes', 'long eyelashes'),
                    ('thick eyelashes', 'thick eyelashes'),
                    ('mascara', 'mascara'),
                    ('eyeshadow', 'eyeshadow'),
                    ('sanpaku', 'sanpaku'),
                    ('bags under', 'bags under eyes'),
                    ('makeup', 'makeup'),
                    ('eyeliner', 'eyeliner'),
                ]
            },
        ]
    },
    {
        'id': 'body',
        'label': 'Body',
        'color': '#34d399',
        'randomize': True,
        'categories': [
            {
                'label': 'Chest',
                'single': True,
                'chips': [
                    ('flat', 'flat chest'),
                    ('small', 'small breasts'),
                    ('medium', 'medium breasts'),
                    ('large', 'large breasts'),
                    ('huge', 'huge breasts'),
                    ('bare', 'bare chest'),
                    ('cleavage', 'cleavage'),
                ]
            },
            {
                'label': 'Figure',
                'single': False,
                'chips': [
                    ('slim', 'slim'),
                    ('petite', 'petite'),
                    ('athletic', 'athletic'),
                    ('curvy', 'curvy'),
                    ('muscular', 'muscular'),
                    ('thick thighs', 'thick thighs'),
                    ('thigh gap', 'thigh gap'),
                    ('wide hips', 'wide hips'),
                    ('large ass', 'large ass'),
                    ('narrow waist', 'narrow waist'),
                    ('abs', 'abs'),
                    ('toned', 'toned'),
                ]
            },
            {
                'label': 'Details',
                'single': False,
                'chips': [
                    ('navel', 'navel'),
                    ('collarbone', 'collarbone'),
                    ('armpits', 'armpits'),
                    ('belly', 'belly'),
                    ('bare belly', 'bare belly'),
                    ('midriff', 'midriff'),
                    ('ass visible through thighs', 'ass visible through thighs'),
                ]
            },
            {
                'label': 'Skin',
                'single': False,
                'chips': [
                    ('light skin', 'light skin'),
                    ('dark skin', 'dark skin'),
                    ('tan', 'tan'),
                    ('pale skin', 'pale skin'),
                    ('tan lines', 'tan lines'),
                    ('freckles', 'freckles'),
                    ('mole', 'mole'),
                    ('scar', 'scar'),
                    ('tattoo', 'tattoo'),
                    ('shiny skin', 'shiny skin'),
                    ('wet', 'wet'),
                ]
            },
            {
                'label': 'Height',
                'single': True,
                'chips': [
                    ('tall', 'tall girl'),
                    ('short', 'short girl'),
                    ('chibi', 'chibi'),
                ]
            },
            {
                'label': 'Age',
                'single': True,
                'chips': [
                    ('young adult', 'young adult'),
                    ('adult', 'adult'),
                    ('mature', 'mature female'),
                    ('elderly', 'old woman'),
                ]
            },
        ]
    },
    {
        'id': 'hair',
        'label': 'Hair',
        'color': '#fbbf24',
        'randomize': True,
        'categories': [
            {
                'label': 'Color',
                'single': False,
                'chips': [
                    ('base › white', 'white hair'),
                    ('base › silver', 'silver hair'),
                    ('base › grey', 'grey hair'),
                    ('base › black', 'black hair'),
                    ('base › dark brown', 'dark brown hair'),
                    ('base › brown', 'brown hair'),
                    ('base › blonde', 'blonde hair'),
                    ('base › golden', 'golden hair'),
                    ('base › red', 'red hair'),
                    ('base › orange', 'orange hair'),
                    ('base › pink', 'pink hair'),
                    ('base › purple', 'purple hair'),
                    ('base › blue', 'blue hair'),
                    ('base › teal', 'teal hair'),
                    ('base › green', 'green hair'),
                    ('base › aqua', 'aqua hair'),
                    ('base › multicolored', 'multicolored hair'),
                    ('base › rainbow', 'rainbow hair'),
                    ('highlights › streaked', 'streaked hair'),
                    ('highlights › gradient', 'gradient hair'),
                    ('highlights › two-tone', 'two-tone hair'),
                    ('highlights › ombre', 'ombre hair'),
                    ('highlights › black inner', 'black inner hair'),
                    ('highlights › white inner', 'white inner hair'),
                    ('highlights › red inner', 'red inner hair'),
                    ('highlights › blonde inner', 'blonde inner hair'),
                    ('highlights › pink inner', 'pink inner hair'),
                    ('highlights › blue inner', 'blue inner hair'),
                    ('highlights › purple inner', 'purple inner hair'),
                    ('highlights › green inner', 'green inner hair'),
                ]
            },
            {
                'label': 'Length',
                'single': True,
                'chips': [
                    ('very short', 'very short hair'),
                    ('short', 'short hair'),
                    ('medium', 'medium hair'),
                    ('shoulder-length', 'shoulder-length hair'),
                    ('long', 'long hair'),
                    ('very long', 'very long hair'),
                    ('absurdly long', 'absurdly long hair'),
                ]
            },
            {
                'label': 'Texture',
                'single': True,
                'chips': [
                    ('straight', 'straight hair'),
                    ('wavy', 'wavy hair'),
                    ('curly', 'curly hair'),
                    ('messy', 'messy hair'),
                    ('fluffy', 'fluffy hair'),
                    ('flowing', 'flowing hair'),
                    ('wet', 'wet hair'),
                    ('shiny', 'shiny hair'),
                    ('spiky', 'spiky hair'),
                    ('ringlets', 'ringlets'),
                    ('drill', 'drill hair'),
                    ('twin drills', 'twin drills'),
                ]
            },
            {
                'label': 'Style',
                'single': False,
                'chips': [
                    ('bangs › wispy', 'wispy bangs'),
                    ('bangs › blunt', 'blunt bangs'),
                    ('bangs › swept', 'swept bangs'),
                    ('bangs › parted', 'parted bangs'),
                    ('bangs › asymmetrical', 'asymmetrical bangs'),
                    ('bangs › diagonal', 'diagonal bangs'),
                    ('bangs › arched', 'arched bangs'),
                    ('bangs › crossed', 'crossed bangs'),
                    ('bangs › choppy', 'choppy bangs'),
                    ('bangs › long bangs', 'long bangs'),
                    ('bangs › short bangs', 'short bangs'),
                    ('bangs › over eyes', 'hair over eyes'),
                    ('bangs › over one eye', 'hair over one eye'),
                    ('bangs › between eyes', 'hair between eyes'),
                    ('bangs › curtained', 'curtained hair'),
                    ('bangs › hime cut', 'hime cut'),
                    ('bangs › dyed bangs', 'dyed bangs'),
                    ('bangs › no bangs', 'no bangs'),
                    ('ponytail › ponytail', 'ponytail'),
                    ('ponytail › high', 'high ponytail'),
                    ('ponytail › low', 'low ponytail'),
                    ('ponytail › side', 'side ponytail'),
                    ('ponytail › folded', 'folded ponytail'),
                    ('ponytail › front', 'front ponytail'),
                    ('ponytail › split', 'split ponytail'),
                    ('ponytail › one side up', 'one side up'),
                    ('ponytail › two side up', 'two side up'),
                    ('twintails › twintails', 'twintails'),
                    ('twintails › low', 'low twintails'),
                    ('twintails › short', 'short twintails'),
                    ('twintails › uneven', 'uneven twintails'),
                    ('twintails › tri tails', 'tri tails'),
                    ('twintails › quad tails', 'quad tails'),
                    ('braid › braid', 'braid'),
                    ('braid › twin braids', 'twin braids'),
                    ('braid › french braid', 'french braid'),
                    ('braid › side braid', 'side braid'),
                    ('braid › crown braid', 'crown braid'),
                    ('braid › braided bun', 'braided bun'),
                    ('braid › half up braid', 'half up braid'),
                    ('braid › low braided', 'low braided long hair'),
                    ('braid › hair rings', 'hair rings'),
                    ('braid › single hair ring', 'single hair ring'),
                    ('bun › bun', 'hair bun'),
                    ('bun › double bun', 'double bun'),
                    ('bun › side bun', 'side bun'),
                    ('bun › half updo', 'half updo'),
                    ('bun › updo', 'updo'),
                    ('bun › high updo', 'high updo'),
                    ('bun › low-tied', 'low-tied long hair'),
                    ('bun › nihongami', 'nihongami'),
                    ('bun › mizura', 'mizura'),
                    ('characteristics › ahoge', 'ahoge'),
                    ('characteristics › huge ahoge', 'huge ahoge'),
                    ('characteristics › antenna', 'antenna hair'),
                    ('characteristics › heart antenna', 'heart antenna hair'),
                    ('characteristics › sidelocks', 'sidelocks'),
                    ('characteristics › long sidelocks', 'long sidelocks'),
                    ('characteristics › single sidelock', 'single sidelock'),
                    ('characteristics › sidelocks tied', 'sidelocks tied back'),
                    ('characteristics › hair tubes', 'hair tubes'),
                    ('characteristics › widow\'s peak', 'widow\'s peak'),
                    ('characteristics › center part', 'center part'),
                    ('characteristics › side part', 'side part'),
                    ('characteristics › floating', 'floating hair'),
                    ('characteristics › wind-blown', 'wind-blown hair'),
                ]
            },
            {
                'label': 'Accessories',
                'single': False,
                'chips': [
                    ('bow', 'hair bow'),
                    ('ribbon', 'hair ribbon'),
                    ('flower', 'hair flower'),
                    ('clip', 'hair clip'),
                    ('hairpin', 'hairpin'),
                    ('ornament', 'hair ornament'),
                    ('tie', 'hair tie'),
                    ('scrunchie', 'scrunchie'),
                    ('band', 'hair band'),
                    ('intakes', 'hair intakes'),
                    ('star ornament', 'star hair ornament'),
                    ('x ornament', 'x hair ornament'),
                ]
            },
        ]
    },
    {
        'id': 'expr',
        'label': 'Expression',
        'color': '#fb923c',
        'randomize': True,
        'categories': [
            {
                'label': 'Positive',
                'single': False,
                'chips': [
                    ('smile', 'smile'),
                    ('grin', 'grin'),
                    ('happy', 'happy'),
                    ('excited', 'excited'),
                    ('laughing', 'laughing'),
                    ('smug', 'smug'),
                    ('playful', 'playful'),
                    ('satisfied', 'satisfied'),
                    ('confident', 'confident'),
                    ('teasing', 'teasing'),
                    ('seductive', 'seductive'),
                    ('joyful', 'joyful'),
                    ('relieved', 'relieved'),
                    ('proud', 'proud'),
                ]
            },
            {
                'label': 'Negative',
                'single': False,
                'chips': [
                    ('sad', 'sad'),
                    ('pout', 'pout'),
                    ('crying', 'crying'),
                    ('angry', 'angry'),
                    ('frustrated', 'frustrated'),
                    ('annoyed', 'annoyed'),
                    ('disgusted', 'disgust'),
                    ('depressed', 'depressed'),
                    ('despair', 'despair'),
                    ('scowl', 'scowl'),
                    ('frown', 'frown'),
                    ('jealous', 'envy'),
                    ('lonely', 'lonely'),
                    ('pain', 'pain'),
                ]
            },
            {
                'label': 'Neutral',
                'single': False,
                'chips': [
                    ('expressionless', 'expressionless'),
                    ('bored', 'bored'),
                    ('confused', 'confused'),
                    ('nervous', 'nervous'),
                    ('embarrassed', 'embarrassed'),
                    ('shy', 'shy'),
                    ('flustered', 'flustered'),
                    ('drunk', 'drunk'),
                    ('sleepy', 'sleepy'),
                    ('tired', 'tired'),
                    ('determined', 'determined'),
                    ('serious', 'serious'),
                    ('disdain', 'disdain'),
                    ('surprised', 'surprised'),
                    ('shocked', 'shocked'),
                    ('curious', 'curious'),
                    ('thoughtful', 'thinking'),
                    ('relaxed', 'relaxed'),
                ]
            },
            {
                'label': 'Mouth',
                'single': False,
                'chips': [
                    ('open mouth', 'open mouth'),
                    ('closed mouth', 'closed mouth'),
                    ('parted lips', 'parted lips'),
                    ('tongue out', 'tongue out'),
                    ('tongue', 'tongue'),
                    ('licking lips', 'licking lips'),
                    ('biting lip', 'biting lip'),
                    ('clenched teeth', 'clenched teeth'),
                    ('teeth', 'teeth'),
                    ('fang', 'fang'),
                    ('fangs', 'fangs'),
                    (':3', ':3'),
                    (':o', ':o'),
                    (':d', ':d'),
                    ('w mouth', 'w'),
                    ('round mouth', 'round mouth'),
                ]
            },
            {
                'label': 'Physical',
                'single': False,
                'chips': [
                    ('blush', 'blush'),
                    ('full-face blush', 'full-face blush'),
                    ('nose blush', 'nose blush'),
                    ('tears', 'tears'),
                    ('teary eyes', 'teary eyes'),
                    ('watery eyes', 'watery eyes'),
                    ('nosebleed', 'nosebleed'),
                    ('sweat', 'sweat'),
                    ('sweatdrop', 'sweatdrop'),
                    ('drool', 'drool'),
                    ('wink', 'one eye closed'),
                    ('closed eyes', 'closed eyes'),
                    ('raised eyebrow', 'raised eyebrow'),
                    ('anger vein', 'anger vein'),
                    ('wide eyes', 'wide eyes'),
                    ('rolling eyes', 'rolling eyes'),
                ]
            },
        ]
    },
    {
        'id': 'clothing',
        'label': 'Clothing',
        'color': '#c084fc',
        'randomize': True,
        'categories': [
            {
                'label': 'Ensemble',
                'single': True,
                'chips': [
                    ('dress › dress', 'dress'),
                    ('dress › sundress', 'sundress'),
                    ('dress › mini dress', 'mini dress'),
                    ('dress › shirt dress', 'shirt dress'),
                    ('dress › gown', 'gown'),
                    ('dress › ballgown', 'ballgown'),
                    ('dress › evening gown', 'evening gown'),
                    ('dress › wedding dress', 'wedding dress'),
                    ('uniform › school uniform', 'school uniform'),
                    ('uniform › sailor uniform', 'sailor uniform'),
                    ('uniform › military uniform', 'military uniform'),
                    ('uniform › police uniform', 'police uniform'),
                    ('uniform › maid', 'maid'),
                    ('uniform › nurse', 'nurse'),
                    ('uniform › waitress', 'waitress'),
                    ('uniform › cheerleader', 'cheerleader uniform'),
                    ('traditional › kimono', 'kimono'),
                    ('traditional › furisode', 'furisode'),
                    ('traditional › yukata', 'yukata'),
                    ('traditional › miko', 'miko'),
                    ('traditional › hakama', 'hakama'),
                    ('traditional › cheongsam', 'cheongsam'),
                    ('traditional › hanfu', 'hanfu'),
                    ('traditional › hanbok', 'hanbok'),
                    ('traditional › ao dai', 'ao dai'),
                    ('traditional › sari', 'sari'),
                    ('traditional › sarong', 'sarong'),
                    ('folk › dirndl', 'dirndl'),
                    ('folk › folk costume', 'folk costume'),
                    ('folk › peasant dress', 'peasant dress'),
                    ('folk › tribal', 'tribal clothing'),
                    ('folk › loincloth', 'loincloth'),
                    ('folk › viking', 'viking'),
                    ('folk › celtic', 'celtic'),
                    ('fantasy › armor', 'armor'),
                    ('fantasy › plate armor', 'plate armor'),
                    ('fantasy › fantasy armor', 'fantasy armor'),
                    ('fantasy › robe', 'robe'),
                    ('fantasy › mage robe', 'mage robe'),
                    ('fantasy › witch dress', 'witch dress'),
                    ('fantasy › gothic lolita', 'gothic lolita'),
                    ('fantasy › lolita', 'lolita'),
                    ('fantasy › nun habit', 'habit'),
                    ('themed › bunny suit', 'bunny suit'),
                    ('themed › santa costume', 'santa costume'),
                    ('themed › gym uniform', 'gym uniform'),
                    ('themed › track suit', 'track suit'),
                    ('themed › jumpsuit', 'jumpsuit'),
                    ('themed › overalls', 'overalls'),
                    ('themed › idol costume', 'idol costume'),
                    ('themed › magical girl', 'magical girl'),
                    ('themed › pirate', 'pirate'),
                    ('themed › ninja', 'ninja'),
                    ('themed › kunoichi', 'kunoichi'),
                    ('themed › cowgirl', 'cowboy hat, western'),
                    ('sci-fi › bodysuit', 'bodysuit'),
                    ('sci-fi › plugsuit', 'plugsuit'),
                    ('sci-fi › latex suit', 'latex suit'),
                    ('sci-fi › catsuit', 'catsuit'),
                    ('sci-fi › pilot suit', 'pilot suit'),
                    ('sci-fi › power armor', 'power armor'),
                    ('sci-fi › exosuit', 'exosuit'),
                    ('sci-fi › space suit', 'space suit'),
                    ('sci-fi › battle suit', 'battle suit'),
                ]
            },
            {
                'label': 'Top',
                'single': True,
                'chips': [
                    ('shirt › shirt', 'shirt'),
                    ('shirt › t-shirt', 't-shirt'),
                    ('shirt › dress shirt', 'dress shirt'),
                    ('shirt › button-up', 'collared shirt'),
                    ('shirt › polo shirt', 'polo shirt'),
                    ('shirt › tube top', 'tube top'),
                    ('shirt › tank top', 'tank top'),
                    ('shirt › camisole', 'camisole'),
                    ('sweater › sweater', 'sweater'),
                    ('sweater › oversized sweater', 'oversized sweater'),
                    ('sweater › turtleneck', 'turtleneck'),
                    ('sweater › crop sweater', 'crop sweater'),
                    ('sweater › cardigan', 'cardigan'),
                    ('sweater › hoodie', 'hoodie'),
                    ('crop › crop top', 'crop top'),
                    ('crop › sports bra', 'sports bra'),
                    ('crop › bikini top', 'bikini top'),
                    ('crop › halter top', 'halter top'),
                    ('crop › bra', 'bra'),
                    ('blouse › blouse', 'blouse'),
                    ('blouse › frilled blouse', 'frilled blouse'),
                    ('blouse › sailor shirt', 'sailor shirt'),
                    ('sarashi', 'sarashi'),
                ]
            },
            {
                'label': 'Bottom',
                'single': True,
                'chips': [
                    ('skirt › skirt', 'skirt'),
                    ('skirt › mini skirt', 'mini skirt'),
                    ('skirt › micro skirt', 'micro skirt'),
                    ('skirt › pleated skirt', 'pleated skirt'),
                    ('skirt › midi skirt', 'midi skirt'),
                    ('skirt › maxi skirt', 'maxi skirt'),
                    ('skirt › pencil skirt', 'pencil skirt'),
                    ('skirt › frilled skirt', 'frilled skirt'),
                    ('skirt › gothic skirt', 'gothic skirt'),
                    ('skirt › slit skirt', 'slit skirt'),
                    ('shorts › shorts', 'shorts'),
                    ('shorts › denim shorts', 'denim shorts'),
                    ('shorts › bike shorts', 'bike shorts'),
                    ('shorts › hot pants', 'hot pants'),
                    ('shorts › micro shorts', 'micro shorts'),
                    ('shorts › board shorts', 'board shorts'),
                    ('pants › pants', 'pants'),
                    ('pants › jeans', 'jeans'),
                    ('pants › skinny pants', 'skinny pants'),
                    ('pants › wide leg pants', 'wide leg pants'),
                    ('pants › harem pants', 'harem pants'),
                    ('pants › cargo pants', 'cargo pants'),
                    ('pants › sweatpants', 'sweatpants'),
                ]
            },
            {
                'label': 'Outerwear',
                'single': False,
                'chips': [
                    ('apron', 'apron'),
                    ('jacket › jacket', 'jacket'),
                    ('jacket › leather jacket', 'leather jacket'),
                    ('jacket › denim jacket', 'denim jacket'),
                    ('jacket › blazer', 'blazer'),
                    ('jacket › military jacket', 'military jacket'),
                    ('jacket › bomber jacket', 'bomber jacket'),
                    ('coat › coat', 'coat'),
                    ('coat › trench coat', 'trench coat'),
                    ('coat › overcoat', 'overcoat'),
                    ('coat › fur coat', 'fur coat'),
                    ('cape › cape', 'cape'),
                    ('cape › capelet', 'capelet'),
                    ('cape › cloak', 'cloak'),
                    ('cape › hooded cloak', 'hooded cloak'),
                ]
            },
            {
                'label': 'Swimwear',
                'single': True,
                'chips': [
                    ('bikini › bikini', 'bikini'),
                    ('bikini › micro bikini', 'micro bikini'),
                    ('bikini › string bikini', 'string bikini'),
                    ('bikini › side-tie bikini', 'side-tie bikini bottom'),
                    ('bikini › sports bikini', 'sports bikini'),
                    ('swimsuit › swimsuit', 'swimsuit'),
                    ('swimsuit › one-piece', 'one-piece swimsuit'),
                    ('swimsuit › school swimsuit', 'school swimsuit'),
                    ('swimsuit › competition swimsuit', 'competition swimsuit'),
                    ('under clothes › swimsuit under clothes', 'swimsuit under clothes'),
                    ('under clothes › bikini under clothes', 'bikini under clothes'),
                    ('under clothes › bikini top under shirt', 'bikini top under shirt'),
                ]
            },
            {
                'label': 'Underwear',
                'single': False,
                'chips': [
                    ('bra › bra', 'bra'),
                    ('bra › sports bra', 'sports bra'),
                    ('bra › strapless bra', 'strapless bra'),
                    ('bra › bralette', 'bralette'),
                    ('bra › lace bra', 'lace bra'),
                    ('bra › frilled bra', 'frilled bra'),
                    ('bra › push-up bra', 'push-up bra'),
                    ('bra › front-hook bra', 'front-hook bra'),
                    ('panties › panties', 'panties'),
                    ('panties › thong', 'thong'),
                    ('panties › g-string', 'g-string'),
                    ('panties › boyshorts', 'boy shorts'),
                    ('panties › bikini panties', 'bikini bottom'),
                    ('panties › lace panties', 'lace panties'),
                    ('panties › frilled panties', 'frilled panties'),
                    ('panties › striped panties', 'striped panties'),
                    ('sets › lingerie', 'lingerie'),
                    ('sets › lingerie set', 'lingerie set'),
                    ('sets › babydoll', 'babydoll'),
                    ('sets › teddy', 'teddy'),
                    ('sets › bodystocking', 'bodystocking'),
                    ('sets › chemise', 'chemise'),
                    ('corsetry › corset', 'corset'),
                    ('corsetry › bustier', 'bustier'),
                    ('corsetry › garter belt', 'garter belt'),
                    ('corsetry › garter', 'garter'),
                    ('corsetry › suspenders', 'suspenders'),
                    ('peek › bra peek', 'bra peek'),
                    ('peek › bra visible', 'bra visible through clothes'),
                    ('peek › panty peek', 'panty peek'),
                    ('peek › pantyshot', 'pantyshot'),
                    ('peek › skirt lift', 'skirt lift'),
                    ('peek › shirt lift', 'shirt lift'),
                    ('peek › wardrobe malfunction', 'wardrobe malfunction'),
                    ('peek › naked apron', 'naked apron'),
                ]
            },
            {
                'label': 'Design',
                'single': False,
                'chips': [
                    ('materials › lace', 'lace'),
                    ('materials › silk', 'silk'),
                    ('materials › velvet', 'velvet'),
                    ('materials › leather', 'leather'),
                    ('materials › denim', 'denim'),
                    ('materials › wool', 'wool'),
                    ('materials › satin', 'satin'),
                    ('materials › latex', 'latex'),
                    ('materials › fishnet', 'fishnet'),
                    ('materials › fur trim', 'fur trim'),
                    ('materials › frills', 'frills'),
                    ('materials › ruffles', 'ruffles'),
                    ('materials › embroidery', 'embroidery'),
                    ('materials › sequins', 'sequins'),
                    ('materials › studs', 'studded'),
                    ('materials › chains', 'chains'),
                    ('materials › feathers', 'feathers'),
                    ('materials › floral print', 'floral print'),
                    ('materials › plaid', 'plaid'),
                    ('materials › striped', 'striped'),
                    ('materials › checkered', 'checkered'),
                    ('materials › polka dot', 'polka dot'),
                    ('shoulders › bare shoulders', 'bare shoulders'),
                    ('shoulders › off shoulder', 'off shoulder'),
                    ('shoulders › single bare shoulder', 'single bare shoulder'),
                    ('shoulders › cold shoulder', 'cold shoulder sleeves'),
                    ('shoulders › strapless', 'strapless'),
                    ('sleeves › sleeveless', 'sleeveless'),
                    ('sleeves › short sleeves', 'short sleeves'),
                    ('sleeves › long sleeves', 'long sleeves'),
                    ('sleeves › wide sleeves', 'wide sleeves'),
                    ('sleeves › oversized sleeves', 'oversized sleeves'),
                    ('sleeves › detached sleeves', 'detached sleeves'),
                    ('sleeves › puffed sleeves', 'puffed sleeves'),
                    ('sleeves › rolled up sleeves', 'rolled up sleeves'),
                    ('sleeves › bell sleeves', 'bell sleeves'),
                    ('neckline › turtleneck', 'turtleneck'),
                    ('neckline › v-neck', 'v-neck'),
                    ('neckline › collared', 'collared'),
                    ('neckline › halter neck', 'halter'),
                    ('neckline › criss-cross halter', 'criss-cross halter'),
                    ('neckline › backless', 'backless'),
                    ('asymmetric › asymmetrical outfit', 'asymmetrical outfit'),
                    ('asymmetric › asymmetrical sleeves', 'asymmetrical sleeves'),
                    ('asymmetric › asymmetrical legwear', 'asymmetrical legwear'),
                    ('asymmetric › single thighhigh', 'single thighhigh'),
                    ('asymmetric › single glove', 'single glove'),
                    ('asymmetric › mismatched legwear', 'mismatched legwear'),
                    ('state › oversized', 'oversized clothes'),
                    ('state › tight', 'tight'),
                    ('state › open jacket', 'open jacket'),
                    ('state › unbuttoned', 'unbuttoned'),
                    ('state › torn clothing', 'torn clothes'),
                    ('state › wet clothing', 'wet clothes'),
                    ('state › see-through', 'see-through'),
                    ('state › sheer', 'sheer'),
                    ('state › revealing', 'revealing clothes'),
                    ('state › midriff', 'midriff'),
                    ('state › low-cut', 'low-cut'),
                ]
            },
        ]
    },
    {
        'id': 'legs',
        'label': 'Legs / Footwear',
        'color': '#22d3ee',
        'randomize': True,
        'categories': [
            {
                'label': 'Hosiery',
                'single': True,
                'chips': [
                    ('bare legs', 'bare legs'),
                    ('thighhighs', 'thighhighs'),
                    ('black thighhighs', 'black thighhighs'),
                    ('white thighhighs', 'white thighhighs'),
                    ('tights', 'tights'),
                    ('stockings', 'stockings'),
                    ('pantyhose', 'pantyhose'),
                    ('fishnet thighhighs', 'fishnet thighhighs'),
                    ('socks', 'socks'),
                    ('ankle socks', 'ankle socks'),
                    ('knee socks', 'knee socks'),
                    ('loose socks', 'loose socks'),
                    ('leg warmers', 'leg warmers'),
                    ('garter straps', 'garter straps'),
                    ('lace thighhighs', 'lace-trimmed thighhighs'),
                    ('frilled socks', 'frilled socks'),
                    ('over-knee socks', 'over-knee socks'),
                    ('mismatched legwear', 'mismatched legwear'),
                    ('single thighhigh', 'single thighhigh'),
                ]
            },
            {
                'label': 'Footwear',
                'single': True,
                'chips': [
                    ('barefoot', 'barefoot'),
                    ('heels › heels', 'high heels'),
                    ('heels › stilettos', 'stiletto heels'),
                    ('heels › platform heels', 'platform heels'),
                    ('heels › wedge heels', 'wedge heels'),
                    ('heels › pumps', 'pumps'),
                    ('boots › boots', 'boots'),
                    ('boots › knee boots', 'knee boots'),
                    ('boots › thigh boots', 'thigh-high boots'),
                    ('boots › ankle boots', 'ankle boots'),
                    ('boots › combat boots', 'combat boots'),
                    ('boots › platform boots', 'platform boots'),
                    ('sneakers', 'sneakers'),
                    ('loafers', 'loafers'),
                    ('mary janes', 'mary janes'),
                    ('sandals', 'sandals'),
                    ('flip flops', 'flip-flops'),
                    ('slippers', 'slippers'),
                    ('geta', 'geta'),
                    ('zouri', 'zouri'),
                ]
            },
        ]
    },
    {
        'id': 'acc',
        'label': 'Accessories',
        'color': '#e879f9',
        'randomize': True,
        'categories': [
            {
                'label': 'Neck',
                'single': False,
                'chips': [
                    ('choker', 'choker'),
                    ('necklace', 'necklace'),
                    ('collar', 'collar'),
                    ('ribbon choker', 'ribbon choker'),
                    ('cross necklace', 'cross necklace'),
                    ('pendant', 'pendant'),
                    ('locket', 'locket'),
                    ('dog tags', 'dog tags'),
                    ('tie', 'necktie'),
                    ('bow tie', 'bow tie'),
                    ('ascot', 'ascot'),
                    ('cravat', 'cravat'),
                    ('neck ribbon', 'neck ribbon'),
                    ('scarf', 'scarf'),
                ]
            },
            {
                'label': 'Wrists & Hands',
                'single': False,
                'chips': [
                    ('gloves', 'gloves'),
                    ('fingerless gloves', 'fingerless gloves'),
                    ('elbow gloves', 'elbow gloves'),
                    ('bracelet', 'bracelet'),
                    ('wristband', 'wristband'),
                    ('wrist cuffs', 'wrist cuffs'),
                    ('arm warmers', 'arm warmers'),
                    ('armband', 'armband'),
                    ('forearm ribbon', 'forearm ribbon'),
                    ('watch', 'watch'),
                    ('ring', 'ring'),
                ]
            },
            {
                'label': 'Eyewear',
                'single': True,
                'chips': [
                    ('glasses › glasses', 'glasses'),
                    ('glasses › round glasses', 'round eyewear'),
                    ('glasses › square glasses', 'square eyewear'),
                    ('glasses › oval glasses', 'oval eyewear'),
                    ('glasses › cat-eye glasses', 'cat-eye glasses'),
                    ('glasses › thick-rimmed', 'thick-rimmed eyewear'),
                    ('glasses › half-rim', 'semi-rimless eyewear'),
                    ('glasses › rimless', 'rimless eyewear'),
                    ('glasses › pince-nez', 'pince-nez'),
                    ('glasses › monocle', 'monocle'),
                    ('sunglasses › sunglasses', 'sunglasses'),
                    ('sunglasses › aviator', 'aviator sunglasses'),
                    ('sunglasses › wayfarer', 'wayfarer sunglasses'),
                    ('sunglasses › shield', 'shield sunglasses'),
                    ('sunglasses › round sunnies', 'round sunglasses'),
                    ('sunglasses › gradient lens', 'gradient sunglasses'),
                    ('sunglasses › mirrored', 'mirrored sunglasses'),
                    ('sunglasses › heart-shaped', 'heart-shaped sunglasses'),
                    ('goggles › goggles', 'goggles'),
                    ('goggles › swim goggles', 'swim goggles'),
                    ('goggles › lab goggles', 'lab coat'),
                    ('goggles › night vision', 'night-vision goggles'),
                    ('visor', 'visor'),
                ]
            },
            {
                'label': 'Headwear',
                'single': False,
                'chips': [
                    ('hat', 'hat'),
                    ('witch hat', 'witch hat'),
                    ('beret', 'beret'),
                    ('cap', 'baseball cap'),
                    ('military cap', 'military cap'),
                    ('mob cap', 'mob cap'),
                    ('nurse cap', 'nurse cap'),
                    ('veil', 'veil'),
                    ('flower crown', 'flower crown'),
                    ('headband', 'headband'),
                    ('ear muffs', 'ear muffs'),
                    ('crown', 'crown'),
                    ('tiara', 'tiara'),
                    ('hood', 'hood'),
                    ('cat ears headband', 'fake animal ears'),
                    ('maid headdress', 'maid headdress'),
                ]
            },
            {
                'label': 'Waist',
                'single': False,
                'chips': [
                    ('belt', 'belt'),
                    ('waist bow', 'waist bow'),
                    ('sash', 'sash'),
                    ('obi', 'obi'),
                ]
            },
            {
                'label': 'Ankle & Feet',
                'single': False,
                'chips': [
                    ('anklet', 'anklet'),
                    ('ankle ribbon', 'ankle ribbon'),
                    ('toe ring', 'toe ring'),
                ]
            },
            {
                'label': 'Misc',
                'single': False,
                'chips': [
                    ('earrings', 'earrings'),
                    ('stud earrings', 'stud earrings'),
                    ('hoop earrings', 'hoop earrings'),
                    ('drop earrings', 'drop earrings'),
                    ('bag', 'bag'),
                    ('backpack', 'backpack'),
                    ('umbrella', 'umbrella'),
                    ('parasol', 'parasol'),
                    ('fan', 'folding fan'),
                    ('mask', 'mask'),
                    ('eye patch', 'eyepatch'),
                    ('tail accessory', 'tail ornament'),
                ]
            },
        ]
    },
    {
        'id': 'pose',
        'label': 'Pose / Action',
        'color': '#a3e635',
        'randomize': True,
        'categories': [
            {
                'label': 'Position',
                'single': False,
                'chips': [
                    ('standing › standing', 'standing'),
                    ('standing › on one leg', 'standing on one leg'),
                    ('standing › tiptoes', 'tiptoes'),
                    ('standing › wide stance', 'wide stance'),
                    ('standing › crossed legs', 'crossed legs'),
                    ('standing › leaning forward', 'leaning forward'),
                    ('standing › leaning back', 'leaning back'),
                    ('standing › leaning on wall', 'leaning on wall'),
                    ('standing › against wall', 'against wall'),
                    ('standing › contrapposto', 'contrapposto'),
                    ('standing › arched back', 'arched back'),
                    ('standing › bent over', 'bent over'),
                    ('sitting › sitting', 'sitting'),
                    ('sitting › on chair', 'sitting on chair'),
                    ('sitting › on floor', 'sitting on floor'),
                    ('sitting › on heels', 'sitting on heels'),
                    ('sitting › kneeling', 'kneeling'),
                    ('sitting › crouching', 'crouching'),
                    ('sitting › squatting', 'squatting'),
                    ('sitting › lotus position', 'lotus position'),
                    ('sitting › knees up', 'knees up'),
                    ('sitting › legs dangling', 'legs dangling'),
                    ('lying › lying', 'lying'),
                    ('lying › on back', 'lying on back'),
                    ('lying › on side', 'on side'),
                    ('lying › on stomach', 'on stomach'),
                    ('lying › sleeping', 'sleeping'),
                    ('lying › reclining', 'reclining'),
                    ('lying › all fours', 'all fours'),
                ]
            },
            {
                'label': 'Arms',
                'single': False,
                'chips': [
                    ('arms up', 'arms up'),
                    ('arms behind back', 'arms behind back'),
                    ('arms behind head', 'arms behind head'),
                    ('arms at sides', 'arms at sides'),
                    ('arms open', 'arms open'),
                    ('crossed arms', 'crossed arms'),
                    ('hands on hips', 'hands on hips'),
                    ('hand on hip', 'hand on hip'),
                    ('hand on chest', 'hand on own chest'),
                    ('hand on face', 'hand on own face'),
                    ('hands clasped', 'hands clasped'),
                    ('hands in pockets', 'hands in pockets'),
                    ('reaching out', 'reaching out'),
                    ('outstretched arm', 'outstretched arm'),
                    ('outstretched hand', 'outstretched hand'),
                ]
            },
            {
                'label': 'Action',
                'single': False,
                'chips': [
                    ('running', 'running'),
                    ('jumping', 'jumping'),
                    ('walking', 'walking'),
                    ('lunging', 'lunging'),
                    ('flying', 'flying'),
                    ('falling', 'falling'),
                    ('fighting stance', 'fighting stance'),
                    ('boxing stance', 'boxing stance'),
                    ('holding weapon', 'holding weapon'),
                    ('holding sword', 'holding sword'),
                    ('casting spell', 'magic circle'),
                    ('eating', 'eating'),
                    ('drinking', 'drinking'),
                    ('reading', 'reading'),
                    ('hugging', 'hug'),
                    ('pointing', 'pointing'),
                    ('waving', 'waving'),
                    ('peace sign', 'v'),
                    ('thumbs up', 'thumbs up'),
                    ('hand heart', 'hand heart'),
                    ('spinning', 'spinning'),
                    ('stretching', 'stretching'),
                ]
            },
            {
                'label': 'Looking',
                'single': False,
                'chips': [
                    ('at viewer', 'looking at viewer'),
                    ('away', 'looking away'),
                    ('to the side', 'looking to the side'),
                    ('up', 'looking up'),
                    ('down', 'looking down'),
                    ('back', 'looking back'),
                    ('down at viewer', 'looking down at viewer'),
                    ('up at viewer', 'looking up at viewer'),
                    ('over shoulder', 'looking over shoulder'),
                    ('at camera', 'looking at camera'),
                ]
            },
            {
                'label': 'Framing',
                'single': False,
                'chips': [
                    ('camera angle › from front', 'facing viewer'),
                    ('camera angle › from behind', 'from behind'),
                    ('camera angle › from side', 'from side'),
                    ('camera angle › profile', 'profile'),
                    ('camera angle › 3/4 view', 'three quarter view'),
                    ('camera angle › from above', 'from above'),
                    ('camera angle › from below', 'from below'),
                    ('camera angle › over the shoulder', 'over the shoulder'),
                    ('camera angle › dutch angle', 'dutch angle'),
                    ('camera angle › fisheye', 'fisheye'),
                    ('camera angle › pov', 'pov'),
                    ('camera angle › close-up', 'close-up'),
                    ('camera angle › extreme close-up', 'extreme close-up'),
                    ('camera angle › foreshortening', 'foreshortening'),
                    ('camera angle › bird\'s eye', 'bird\'s-eye view'),
                    ('camera angle › worm\'s eye', 'worm\'s-eye view'),
                    ('composition › centered', 'centered'),
                    ('composition › off-center', 'off-center'),
                    ('composition › rule of thirds', 'rule of thirds'),
                    ('composition › symmetrical', 'symmetrical'),
                    ('composition › asymmetrical', 'asymmetrical layout'),
                    ('composition › negative space', 'negative space'),
                    ('composition › foreground focus', 'foreground'),
                    ('composition › background focus', 'background focus'),
                    ('composition › framed', 'framed'),
                    ('composition › silhouette', 'silhouette'),
                ]
            },
        ]
    },
    {
        'id': 'bg',
        'label': 'Background / Setting',
        'color': '#34d399',
        'randomize': True,
        'categories': [
            {
                'label': 'Location',
                'single': True,
                'chips': [
                    ('simple background', 'simple background'),
                    ('white background', 'white background'),
                    ('black background', 'black background'),
                    ('gradient background', 'gradient background'),
                    ('outdoors', 'outdoors'),
                    ('indoors', 'indoors'),
                    ('urban › city', 'city'),
                    ('urban › cityscape', 'cityscape'),
                    ('urban › city ruins', 'city ruins'),
                    ('urban › rooftop', 'rooftop'),
                    ('urban › street', 'street'),
                    ('urban › alley', 'alley'),
                    ('urban › market', 'market'),
                    ('urban › park', 'park'),
                    ('urban › bridge', 'bridge'),
                    ('urban › cyberpunk city', 'cyberpunk city'),
                    ('nature › forest', 'forest'),
                    ('nature › bamboo forest', 'bamboo forest'),
                    ('nature › beach', 'beach'),
                    ('nature › ocean', 'ocean'),
                    ('nature › mountains', 'mountains'),
                    ('nature › cliff', 'cliff'),
                    ('nature › meadow', 'meadow'),
                    ('nature › flower field', 'flower field'),
                    ('nature › lake', 'lake'),
                    ('nature › river', 'river'),
                    ('nature › waterfall', 'waterfall'),
                    ('nature › cave', 'cave'),
                    ('nature › desert', 'desert'),
                    ('nature › tundra', 'tundra'),
                    ('nature › swamp', 'swamp'),
                    ('nature › island', 'island'),
                    ('interior › bedroom', 'bedroom'),
                    ('interior › classroom', 'classroom'),
                    ('interior › library', 'library'),
                    ('interior › cafe', 'cafe'),
                    ('interior › restaurant', 'restaurant'),
                    ('interior › bathroom', 'bathroom'),
                    ('interior › kitchen', 'kitchen'),
                    ('interior › living room', 'living room'),
                    ('interior › hallway', 'hallway'),
                    ('interior › school hallway', 'school hallway'),
                    ('interior › gym', 'gymnasium'),
                    ('interior › hospital', 'hospital'),
                    ('interior › office', 'office'),
                    ('fantasy › castle', 'castle'),
                    ('fantasy › dungeon', 'dungeon'),
                    ('fantasy › ruins', 'ruins'),
                    ('fantasy › shrine', 'shrine'),
                    ('fantasy › temple', 'temple'),
                    ('fantasy › medieval town', 'medieval town'),
                    ('fantasy › floating island', 'floating island'),
                    ('fantasy › wasteland', 'wasteland'),
                    ('fantasy › underworld', 'underworld'),
                    ('fantasy › space', 'space'),
                    ('fantasy › outer space', 'outer space'),
                ]
            },
            {
                'label': 'Region',
                'single': True,
                'chips': [
                    ('japanese', 'japanese architecture'),
                    ('chinese', 'chinese architecture'),
                    ('european', 'european architecture'),
                    ('victorian', 'victorian'),
                    ('arabic', 'arabic architecture'),
                    ('edo period', 'edo period'),
                    ('medieval', 'medieval'),
                    ('ancient greek', 'ancient greek'),
                    ('ancient egyptian', 'ancient egypt'),
                    ('futuristic', 'futuristic city'),
                    ('post-apocalyptic', 'post-apocalyptic'),
                ]
            },
            {
                'label': 'Season',
                'single': True,
                'chips': [
                    ('spring', 'spring (season)'),
                    ('summer', 'summer'),
                    ('autumn', 'autumn'),
                    ('winter', 'winter'),
                    ('cherry blossoms', 'cherry blossoms'),
                    ('falling leaves', 'falling leaves'),
                    ('autumn leaves', 'autumn leaves'),
                    ('snow', 'snow'),
                    ('snowfall', 'snowfall'),
                    ('sunflowers', 'sunflowers'),
                ]
            },
            {
                'label': 'Time of Day',
                'single': True,
                'chips': [
                    ('day', 'day'),
                    ('night', 'night'),
                    ('sunrise', 'sunrise'),
                    ('sunset', 'sunset'),
                    ('dawn', 'dawn'),
                    ('dusk', 'dusk'),
                    ('midnight', 'midnight'),
                    ('golden hour', 'golden hour'),
                    ('blue hour', 'blue hour'),
                ]
            },
            {
                'label': 'Weather',
                'single': False,
                'chips': [
                    ('clear sky', 'clear sky'),
                    ('cloudy', 'cloudy sky'),
                    ('rain', 'rain'),
                    ('heavy rain', 'heavy rain'),
                    ('snow', 'snowing'),
                    ('fog', 'fog'),
                    ('mist', 'mist'),
                    ('wind', 'wind'),
                    ('storm', 'storm'),
                    ('lightning', 'lightning'),
                    ('rainbow', 'rainbow'),
                ]
            },
            {
                'label': 'Effects',
                'single': False,
                'chips': [
                    ('sky › gradient sky', 'gradient sky'),
                    ('sky › dramatic sky', 'dramatic sky'),
                    ('sky › colorful sky', 'colorful sky'),
                    ('sky › starry sky', 'starry sky'),
                    ('sky › milky way', 'milky way'),
                    ('sky › aurora', 'aurora'),
                    ('sky › moon', 'moon'),
                    ('sky › full moon', 'full moon'),
                    ('sky › crescent moon', 'crescent moon'),
                    ('particles › petals', 'petals'),
                    ('particles › falling petals', 'falling petals'),
                    ('particles › leaves', 'leaves'),
                    ('particles › fireflies', 'fireflies'),
                    ('particles › sparkles', 'sparkle'),
                    ('particles › butterflies', 'butterfly'),
                    ('particles › birds', 'bird'),
                    ('particles › dust', 'dust'),
                    ('particles › smoke', 'smoke'),
                    ('particles › embers', 'embers'),
                    ('atmosphere › blurry background', 'blurry background'),
                    ('atmosphere › blurry foreground', 'blurry foreground'),
                    ('atmosphere › depth of field', 'depth of field'),
                    ('atmosphere › haze', 'haze'),
                    ('atmosphere › dramatic', 'dramatic'),
                    ('atmosphere › moody', 'moody'),
                    ('atmosphere › dreamy', 'dreamy'),
                    ('atmosphere › ethereal', 'ethereal'),
                    ('atmosphere › cozy', 'cozy'),
                    ('atmosphere › ominous', 'ominous'),
                    ('atmosphere › serene', 'serene'),
                    ('atmosphere › wistful', 'wistful'),
                    ('conditions › dilapidated', 'dilapidated'),
                    ('conditions › abandoned', 'abandoned'),
                    ('conditions › overgrown', 'overgrown'),
                    ('conditions › weeds', 'weeds'),
                    ('conditions › moss', 'moss'),
                    ('conditions › rust', 'rust'),
                    ('conditions › graffiti', 'graffiti'),
                    ('conditions › flooded', 'flooded'),
                    ('conditions › underwater', 'underwater'),
                    ('conditions › on fire', 'fire'),
                    ('conditions › frozen', 'frozen'),
                    ('conditions › ice', 'ice'),
                    ('conditions › destroyed', 'destroyed'),
                    ('details › trees', 'tree'),
                    ('details › grass', 'grass'),
                    ('details › flowers', 'flower'),
                    ('details › water surface', 'water surface'),
                    ('details › rocks', 'rock'),
                    ('details › path', 'path'),
                    ('details › fence', 'fence'),
                    ('details › lamp post', 'lamp post'),
                    ('details › shade', 'shade'),
                    ('details › shadow', 'shadow'),
                    ('details › reflection', 'reflection'),
                    ('details › puddle', 'puddle'),
                    ('details › window', 'window'),
                ]
            },
            {
                'label': 'Lighting',
                'single': False,
                'chips': [
                    ('light source › sunlight', 'sunlight'),
                    ('light source › moonlight', 'moonlight'),
                    ('light source › candlelight', 'candlelight'),
                    ('light source › firelight', 'firelight'),
                    ('light source › neon lights', 'neon lights'),
                    ('light source › god rays', 'god rays'),
                    ('light source › dappled light', 'dappled light'),
                    ('light source › lens flare', 'lens flare'),
                    ('style › dramatic lighting', 'dramatic lighting'),
                    ('style › cinematic lighting', 'cinematic lighting'),
                    ('style › soft lighting', 'soft lighting'),
                    ('style › backlighting', 'backlighting'),
                    ('style › rim lighting', 'rim lighting'),
                    ('style › ambient occlusion', 'ambient occlusion'),
                    ('style › bloom', 'bloom'),
                    ('style › volumetric', 'volumetric lighting'),
                    ('focus › depth of field', 'depth of field'),
                    ('focus › bokeh', 'bokeh'),
                    ('focus › motion blur', 'motion blur'),
                    ('focus › sharp focus', 'sharp focus'),
                    ('focus › blurry background', 'blurry background'),
                    ('focus › blurry foreground', 'blurry foreground'),
                ]
            },
            {
                'label': 'Shot',
                'single': True,
                'chips': [
                    ('portrait', 'portrait'),
                    ('close-up', 'close-up'),
                    ('face focus', 'face focus'),
                    ('bust', 'bust'),
                    ('upper body', 'upper body'),
                    ('cowboy shot', 'cowboy shot'),
                    ('lower body', 'lower body'),
                    ('full body', 'full body'),
                    ('wide shot', 'wide shot'),
                    ('panorama', 'panorama'),
                ]
            },
            {
                'label': 'Enhancers',
                'single': False,
                'chips': [
                    ('shiny skin', 'shiny skin'),
                    ('shiny hair', 'shiny hair'),
                    ('glossy', 'glossy'),
                    ('bloom', 'bloom'),
                    ('lens flare', 'lens flare'),
                ]
            },
        ]
    },
    {
        'id': 'style',
        'label': 'Style / Theme',
        'color': '#22d3ee',
        'randomize': False,
        'categories': [
            {
                'label': 'Medium',
                'single': False,
                'chips': [
                    ('anime coloring', 'anime coloring'),
                    ('anime screencap', 'anime screencap'),
                    ('cel shading', 'cel shading'),
                    ('watercolor', 'watercolor'),
                    ('lineart', 'lineart'),
                    ('sketch', 'sketch'),
                    ('illustration', 'illustration'),
                    ('very awa', 'very awa'),
                    ('thin lineart', 'thin lineart'),
                    ('flat color', 'flat color'),
                    ('soft shading', 'soft shading'),
                    ('painterly', 'painterly'),
                ]
            },
            {
                'label': 'Theme',
                'single': False,
                'chips': [
                    ('fantasy', 'fantasy'),
                    ('sci-fi', 'science fiction'),
                    ('cyberpunk', 'cyberpunk'),
                    ('steampunk', 'steampunk'),
                    ('historical', 'historical'),
                    ('modern', 'modern'),
                    ('horror', 'horror'),
                    ('slice of life', 'slice of life'),
                    ('action', 'action'),
                    ('romance', 'romance'),
                    ('dark fantasy', 'dark fantasy'),
                    ('moe', 'moe'),
                ]
            },
        ]
    },
]

# ═══════════════════════════════════════════════════════════════════════════════
# MODEL PRESETS — Best prompt formats based on CivitAI community guides
# ═══════════════════════════════════════════════════════════════════════════════

MODEL_PRESETS = {
    "SDXL Base": {
        "pos_prefix": "masterpiece, best quality, ultra-detailed, highres, 8k",
        "neg_default": "text, logo, watermark, patreon username, deformed hands, extra fingers, unnatural eyes, asymmetric face, blurry, oversaturated, low contrast, jpeg artifacts, bad anatomy, worst quality, low quality",
        "sampler": "DPM++ 2M Karras",
        "steps": 28,
        "cfg": 7,
        "desc": "General SDXL — natural language + tags hybrid",
    },
    "Illustrious XL": {
        "pos_prefix": "masterpiece, best quality, amazing quality, very aesthetic, newest",
        "neg_default": "bad quality, worst quality, worst detail, sketch, censor, lowres, bad anatomy, bad hands, extra digits, fewer digits, missing fingers, extra limbs, jpeg artifacts, watermark, signature, username, artist name, text",
        "sampler": "Euler a",
        "steps": 28,
        "cfg": 7,
        "desc": "WAI Illustrious — Danbooru tag-based",
    },
    "Pony Diffusion": {
        "pos_prefix": "score_9, score_8_up, score_7_up, score_6_up, score_5_up, score_4_up, source_pony",
        "neg_default": "score_6, score_5, score_4, source_furry, source_cartoon, 3d, realistic, photorealistic",
        "sampler": "DPM++ 2M Karras",
        "steps": 25,
        "cfg": 7,
        "desc": "Pony — score-based quality system",
    },
    "Flux": {
        "pos_prefix": "masterpiece, best quality, photo-realistic, sharp focus, ultra-detailed, dramatic lighting",
        "neg_default": "text, logo, watermark, deformed hands, extra fingers, unnatural eyes, blurry, oversaturated, low contrast, cartoon, anime, illustration, drawing",
        "sampler": "Euler",
        "steps": 20,
        "cfg": 1,
        "desc": "Flux Realistic — photographic language",
    },
    "Animagine XL": {
        "pos_prefix": "masterpiece, best quality, very aesthetic, newest, detailed",
        "neg_default": "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry",
        "sampler": "Euler a",
        "steps": 28,
        "cfg": 7,
        "desc": "Animagine — hybrid tag + natural language",
    },
}

# ═══════════════════════════════════════════════════════════════════════════════
# HEX PALETTE CHALLENGE
# ═══════════════════════════════════════════════════════════════════════════════

HEX_PALETTES = [
    {"name": "Sakura Sunset",   "colors": ["#FFB7C5", "#FF69B4", "#FF1493", "#C71585", "#DB7093"]},
    {"name": "Ocean Deep",      "colors": ["#006994", "#008B8B", "#20B2AA", "#48D1CC", "#5F9EA0"]},
    {"name": "Forest Spirit",   "colors": ["#228B22", "#32CD32", "#90EE90", "#006400", "#556B2F"]},
    {"name": "Twilight Sky",    "colors": ["#4B0082", "#8A2BE2", "#9400D3", "#9932CC", "#BA55D3"]},
    {"name": "Golden Hour",     "colors": ["#FFD700", "#FFA500", "#FF8C00", "#FF4500", "#DAA520"]},
    {"name": "Monochrome",      "colors": ["#000000", "#333333", "#666666", "#999999", "#CCCCCC"]},
    {"name": "Cyberpunk Neon",  "colors": ["#FF00FF", "#00FFFF", "#FFFF00", "#FF0080", "#00FF80"]},
    {"name": "Warm Earth",      "colors": ["#8B4513", "#A0522D", "#CD853F", "#D2691E", "#DEB887"]},
    {"name": "Arctic Frost",    "colors": ["#B0E0E6", "#ADD8E6", "#87CEEB", "#00BFFF", "#1E90FF"]},
    {"name": "Royal Decadence", "colors": ["#800080", "#4B0082", "#483D8B", "#6A5ACD", "#9370DB"]},
]
